#! /bin/bash
# usage: sudo ./install

service=influxed-statsd
dest_path=/opt/$service
rm -rf $dest_path
cp -r `pwd` $dest_path
cp init.d/$service /etc/init.d

cd /etc/init.d
chmod +x $service
chkconfig --add $service
chkconfig $service on
