#! /bin/bash
# usage: sudo ./uninstall

service=influxed-statsd
dest_path=/opt/$service

cd /etc/init.d
chkconfig $service off
chkconfig --del $service
rm -f $service
echo "[INFO] service uninstalled"

rm -rf $dest_pathi
echo "[INFO] program files remove"
